[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autonetops"
version = "0.1.0"
dependencies = [
    "click>=8.1.7",
    "jinja2>=3.1.2",
    "netmiko>=4.1.0",
    "pyyaml>=6.0",
]
requires-python = ">=3.6"